# ~/.config/hypr/modules/autostart.conf

exec-once = swww-daemon
exec-once = ~/.config/hypr/scripts/load-theme.sh

exec-once = waybar

exec-once = nm-applet --indicator
exec-once = fcitx5 -d

exec-once = udiskie --automount --notify
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = blueman-applet
