general {
    gaps_in = 2
    gaps_out = 4
    border_size = 1

    col.active_border = rgba(66bbffff) rgba(bbddffff) 45deg
    col.inactive_border = rgba(aaaaaa88)

    layout = dwindle
}

decoration {
    rounding = 2

    active_opacity = 0.99
    inactive_opacity = 0.95
}
